# This is a basic workflow that is manually triggered

name: My testing GHA

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Dimitris'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

      name2:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Kostas'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job0:
    name: Prep-job
    runs-on: ubuntu-latest
    steps:
    - name: Output Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"
    #- uses: m-s-abeer/update-gha-summary-with-workflow-inputs@v1
  job1:
    name:  "Test flow [Name: ${{ github.event.inputs.name }}, Name2: ${{ github.event.inputs.name2 }}]"
    runs-on: ubuntu-latest
      # You can specify the runner you want to use
    environment: test-approval

    steps:
    - name: Job 1 Step
      run:  echo "Hello ${{ inputs.name }}"
    - name: Job 1 Step 2
      run:  echo "How are you today?"
    - name: Job 1 Step 3
      run:  echo "All the best ${{ inputs.name }}"
    - name: Job 1 Step 4
      run:  echo "Nice seeing you today"
 

  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest  # You can specify the runner you want to use

    steps:
    - name: Job 2 Step
      run:  echo "Hello ${{ inputs.name2 }}"
 