# This is a basic workflow that is manually triggered

name: My testing GHA

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Dimitris'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

      name2:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Kostas'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest  # You can specify the runner you want to use

    steps:
    - name: Job 1 Step
      run:  echo "Hello ${{ inputs.name }}"
       

  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest  # You can specify the runner you want to use

    steps:
    - name: Job 2 Step
      run:  echo "Hello ${{ inputs.name2 }}"
    

        
        
